


INSERT INTO APP.RESIDENTPROFILEENTITY (ADDRESS, EMAIL, "NAME", NICKNAME, PHONENUMBER, PREFERENCES, PROOFOFRESIDENCE, NEIGHBORHOOD_ID) 
	VALUES ('8701 Ocean Drive', 'my_email99@gmail.com', 'Andy Ortiz', 'renegade', '8138410566', 'None', 'link', 1);
INSERT INTO APP.RESIDENTPROFILEENTITY (ADDRESS, EMAIL, "NAME", NICKNAME, PHONENUMBER, PREFERENCES, PROOFOFRESIDENCE, NEIGHBORHOOD_ID) 
	VALUES ('Cra 1 # 4 - 25', 'PEDRO10.GOMEZ@msn.com', 'PEDRO GOMEZ', 'PERSONA_NATURAL', '869924884', 'NN', 'PROOF.PDF', 1);
INSERT INTO APP.RESIDENTPROFILEENTITY (ADDRESS, EMAIL, "NAME", NICKNAME, PHONENUMBER, PREFERENCES, PROOFOFRESIDENCE, NEIGHBORHOOD_ID) 
	VALUES ('Cra 1 # 4 - 25', 'PEDRO10.GOMEZ@msn.com', 'PEDRO GOMEZ', 'PERSONA_NATURAL', '869924884', 'NN', 'PROOF.PDF', 1);
INSERT INTO APP.RESIDENTLOGINENTITY (GOVERNMENTID, ISACTIVE, PASSWORD, USERNAME, NEIGHBORHOOD_ID, RESIDENT_ID) 
	VALUES ('281287337', 0, 'Password##1', 'aortiz49', 1, NULL);
INSERT INTO APP.RESIDENTLOGINENTITY (GOVERNMENTID, ISACTIVE, PASSWORD, USERNAME, NEIGHBORHOOD_ID, RESIDENT_ID) 
	VALUES ('281287337', 0, 'Password##1', 'aortisdz49', 200, 101);
INSERT INTO APP.RESIDENTLOGINENTITY (GOVERNMENTID, ISACTIVE, PASSWORD, USERNAME, NEIGHBORHOOD_ID, RESIDENT_ID) 
	VALUES ('281287337', 0, 'Password##1', 'aortsadiz49', 200, 102);


INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('NN', NULL, '2000-10-19', 'NN', 1, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Sheets and, the. Standard electronic standard aldus it ipsum.', 76, '2019-05-22', 'Sheets And Software Ipsum', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('And ever, dummy. When an aldus make unchanged  the.', 25, '2012-11-08', 'And Ever A The', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Sheets a, only. Publishing lorem 1500s, simply of software.', 80, '2015-09-13', 'Sheets a Ever Software', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Remaining ipsum, leap. Ipsum with ipsum is software essentially lorem.', 10, '2014-07-09', 'Remaining Ipsum Remaining Lorem', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Lorem it, essentially. But not ipsum  an desktop ipsum .', 62, '2014-06-16', 'Lorem It Desktop Ipsum ', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('And also, and. An simply lorem survived 1960s sheets.', 13, '2016-02-28', 'And Also Took Sheets', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Has ipsum is, containing. A with industry  scrambled unchanged  been.', 6, '2018-12-28', 'Has Ipsum Is Text Been', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Was ipsum , since. More lorem with lorem unknown dummy.', 42, '2018-11-20', 'Was Ipsum  Including Dummy', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Specimen text, five. Galley when ipsum is and a it.', 16, '2015-05-18', 'Specimen Text Aldus It', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Printing passages,, essentially. Like has when ipsum  a printer.', 87, '2011-01-20', 'Printing Passages, The Printer', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Simply of, was. The passages, the leap a standard.', 19, '2010-11-30', 'Simply Of Letraset Standard', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Standard leap, it. Popularised specimen a ipsum  sheets including.', 18, '2011-12-16', 'Standard Leap Survived Including', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Like centuries,, typesetting. But popularised lorem has including five.', 84, '2013-07-24', 'Like Centuries, The Five', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Of 1500s,, printing. A of standard the 1500s, desktop.', 67, '2016-08-11', 'Of 1500s, Popularised Desktop', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Specimen into, desktop. 1960s lorem essentially book  unchanged  recently.', 66, '2019-05-03', 'Specimen Into Electronic Recently', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Type including, printing. A to of in scrambled printing.', 83, '2013-02-17', 'Type Including It Printing', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Scrambled passages,, ipsum. Like the printing make took printing.', 16, '2012-05-29', 'Scrambled Passages, Letraset Printing', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('1960s been, type. Publishing with industrys industrys it a.', 64, '2010-11-07', '1960s Been Ipsum A', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('The popularised, not. Text type the of printer with.', 31, '2017-10-13', 'The Popularised Of With', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('The lorem, a. A survived ever specimen has to.', 84, '2018-06-19', 'The Lorem Book  To', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Into took, centuries,. Printer specimen more an with printing.', 57, '2012-03-24', 'Into Took Industrys Printing', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('It the, and. An release versions a dummy in.', 44, '2010-12-01', 'It The And In', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('When book , letraset. Specimen in lorem of the book .', 16, '2010-04-23', 'When Book  The Book ', 102, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('1500s, with, sheets. And 1960s passages, containing of not.', 58, '2019-07-20', '1500s, With Ipsum Not', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Type lorem, five. Electronic ipsum remaining the an also.', 29, '2014-09-19', 'Type Lorem Lorem Also', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Specimen sheets, lorem. Took has of dummy printer a.', 52, '2014-01-09', 'Specimen Sheets To A', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('More like, it. It pagemaker not also survived like.', 5, '2016-10-25', 'More Like Release Like', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Been simply, scrambled. Desktop ipsum  typesetting, printer unknown versions.', 70, '2019-08-13', 'Been Simply To Versions', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Passages, with, unknown. The to essentially ipsum industrys to.', 62, '2014-04-30', 'Passages, With Lorem To', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Leap release, survived. Ipsum industry  essentially versions has standard.', 93, '2016-07-04', 'Leap Release Scrambled Standard', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Text not, unchanged . Passages, since also recently sheets letraset.', 55, '2019-07-18', 'Text Not It Letraset', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('But ipsum, lorem. But remaining survived galley has software.', 82, '2010-01-12', 'But Ipsum 1960s Software', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Into also, electronic. Remaining galley ipsum  printing of unchanged .', 82, '2014-07-16', 'Into Also To Unchanged ', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('Specimen ipsum is, has. Of was and also unchanged  the.', 71, '2016-08-03', 'Specimen Ipsum Is The The', 101, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('NN', NULL, '2000-10-19', 'NN', 1, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('NN', NULL, '2000-10-19', 'NN', 1, NULL, NULL);
INSERT INTO APP.POSTENTITY (DESCRIPTION, NUMBEROFLIKES, PUBLISHDATE, TITLE, AUTHOR_ID, BUSINESS_ID, GROUP_ID) 
	VALUES ('NN', NULL, '2000-10-19', 'NN', 101, NULL, NULL);
